version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: nuxgame_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - nuxgame_network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nuxgame_nginx
    restart: unless-stopped
    ports:
      - "8077:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nuxgame_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: nuxgame_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: nuxgame
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: nuxgame_user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - nuxgame_network

  adminer:
    image: adminer
    container_name: nuxgame_adminer
    restart: unless-stopped
    ports:
      - "8078:8080"
    networks:
      - nuxgame_network
    depends_on:
      - db

networks:
  nuxgame_network:
    driver: bridge

volumes:
  dbdata:
    driver: local